version: "3.8"

services:
  gateway_service:
    container_name: gateway_service
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    ports:
      - "3001:5001"
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GATEWAY_BUZZ_SERVICE_ADDR=${GATEWAY_BUZZ_SERVICE_ADDR}
      - GATEWAY_FUZZ_SERVICE_ADDR=${GATEWAY_FUZZ_SERVICE_ADDR}
    networks:
      - tx
    depends_on:
      buzz_service:
        condition: service_healthy
      fuzz_service:
        condition: service_healthy

  buzz_service:
    container_name: buzz_service
    build:
      context: ./service_buzz
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - ADD_SERVICE_BUZZ=${ADD_SERVICE_BUZZ}
    # ports:
    #   - "3002:5002"
    networks:
      - tx
    healthcheck:
      test: "exit 0"

  fuzz_service:
    container_name: fuzz_service
    build:
      context: ./service_fuzz
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - ADD_SERVICE_FUZZ=${ADD_SERVICE_FUZZ}
    # ports:
    #   - "3003:5003"
    #   - "9000:9000"
    networks:
      - tx
    healthcheck:
      test: "exit 0"

networks:
  tx:
    driver: bridge
