### Gateway fuzz
POST http://localhost:3055/fuzz
# apiKey: APILAYER_APIKEY
Content-Type: application/json

{
  "str": "Ping"
}


### Gateway buzz
POST http://localhost:3055/buzz
# apiKey: APILAYER_APIKEY
Content-Type: application/json

{
  "str": "Ping"
}