// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: buzz.proto

package buzz_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BuzzService_Ping_FullMethodName = "/buzz.BuzzService/Ping"
)

// BuzzServiceClient is the client API for BuzzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuzzServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type buzzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuzzServiceClient(cc grpc.ClientConnInterface) BuzzServiceClient {
	return &buzzServiceClient{cc}
}

func (c *buzzServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, BuzzService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuzzServiceServer is the server API for BuzzService service.
// All implementations must embed UnimplementedBuzzServiceServer
// for forward compatibility
type BuzzServiceServer interface {
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedBuzzServiceServer()
}

// UnimplementedBuzzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBuzzServiceServer struct {
}

func (UnimplementedBuzzServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBuzzServiceServer) mustEmbedUnimplementedBuzzServiceServer() {}

// UnsafeBuzzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuzzServiceServer will
// result in compilation errors.
type UnsafeBuzzServiceServer interface {
	mustEmbedUnimplementedBuzzServiceServer()
}

func RegisterBuzzServiceServer(s grpc.ServiceRegistrar, srv BuzzServiceServer) {
	s.RegisterService(&BuzzService_ServiceDesc, srv)
}

func _BuzzService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuzzServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuzzService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuzzServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuzzService_ServiceDesc is the grpc.ServiceDesc for BuzzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuzzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buzz.BuzzService",
	HandlerType: (*BuzzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BuzzService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buzz.proto",
}
